name: Deploy

on:
  push:
    branches:
      - main  # or any other branch you use for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: production  # The name of the environment where you've configured your secrets
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Ensure this matches your project's requirements

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          # Run your application or deployment script here
          python3 app.py
